alter table aparelho_has_peca drop foreign key FKm66eqxxk7jmssmnpw5093pga7;
alter table aparelho_has_peca drop foreign key FK3i2494pwwba6l0thctts5krct;
alter table Aparelho_OrdemDeServico drop foreign key FKfnf845j2vwxb2o13rrsq0c3vf;
alter table Aparelho_OrdemDeServico drop foreign key FKn125ejmqinuofv5qax9mxbrdy;
alter table Cliente_OrdemDeServico drop foreign key FKf7khusadi8dptyqantywl8fd5;
alter table Cliente_OrdemDeServico drop foreign key FKjsusjwv1u16vg7xpnd7g37d11;
alter table OrdemDeServico drop foreign key FK9ljmpgeu7p996trp7qyv4yh0o;
alter table OrdemDeServico drop foreign key FKr6s3o874lp26l7c5htt6ql9q3;
alter table os_has_aparelho drop foreign key FKkjmovksevvep8lmlx2j98go0w;
alter table os_has_aparelho drop foreign key FK1nltffxe3iqlpjhfl9qfnxsye;
alter table Usuario_OrdemDeServico drop foreign key FKqp4r1e57ybgwh65ojkx5cktpp;
alter table Usuario_OrdemDeServico drop foreign key FKsnajuq2wkfrvesgo4wiqm7mje;
drop table if exists Aparelho;
drop table if exists aparelho_has_peca;
drop table if exists Aparelho_OrdemDeServico;
drop table if exists Cliente;
drop table if exists Cliente_OrdemDeServico;
drop table if exists hibernate_sequence;
drop table if exists OrdemDeServico;
drop table if exists os_has_aparelho;
drop table if exists Peca;
drop table if exists Usuario;
drop table if exists Usuario_OrdemDeServico;
create table Aparelho (id integer not null auto_increment, autorizado bit not null, maoDeObra double precision, marca varchar(255), modelo varchar(255), pronto bit not null, serial varchar(255), primary key (id));
create table aparelho_has_peca (aparelho_id integer not null, peca_id integer not null);
create table Aparelho_OrdemDeServico (Aparelho_id integer not null, listaOs_id integer not null);
create table Cliente (id integer not null, CPF varchar(255), Endereco varchar(255), celular varchar(255), cidade tinyblob, email varchar(255), nome varchar(255), rg varchar(255), telefone varchar(255), primary key (id));
create table Cliente_OrdemDeServico (Cliente_id integer not null, listaOrdemServico_id integer not null);
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
create table OrdemDeServico (id integer not null auto_increment, dataEntrada datetime, dataRetornoEntrada datetime, dataRetornoSaida datetime, dataSaida datetime, maoDeObra float not null, totalOrcamento float not null, cliente_id integer, usuario_id integer, primary key (id));
create table os_has_aparelho (ordemDeServico_id integer not null, aparelho_id integer not null);
create table Peca (id integer not null auto_increment, nome varchar(255), preco float not null, primary key (id));
create table Usuario (id integer not null auto_increment, nome varchar(255), senha varchar(255), primary key (id));
create table Usuario_OrdemDeServico (Usuario_id integer not null, listaOsCadastrada_id integer not null);
alter table Cliente_OrdemDeServico add constraint UK_eyuwc147fa7h4xxxq49lovkl0 unique (listaOrdemServico_id);
alter table Usuario_OrdemDeServico add constraint UK_q027fftybejq30groh3qih7lf unique (listaOsCadastrada_id);
alter table aparelho_has_peca add constraint FKm66eqxxk7jmssmnpw5093pga7 foreign key (peca_id) references Peca (id);
alter table aparelho_has_peca add constraint FK3i2494pwwba6l0thctts5krct foreign key (aparelho_id) references Aparelho (id);
alter table Aparelho_OrdemDeServico add constraint FKfnf845j2vwxb2o13rrsq0c3vf foreign key (listaOs_id) references OrdemDeServico (id);
alter table Aparelho_OrdemDeServico add constraint FKn125ejmqinuofv5qax9mxbrdy foreign key (Aparelho_id) references Aparelho (id);
alter table Cliente_OrdemDeServico add constraint FKf7khusadi8dptyqantywl8fd5 foreign key (listaOrdemServico_id) references OrdemDeServico (id);
alter table Cliente_OrdemDeServico add constraint FKjsusjwv1u16vg7xpnd7g37d11 foreign key (Cliente_id) references Cliente (id);
alter table OrdemDeServico add constraint FK9ljmpgeu7p996trp7qyv4yh0o foreign key (cliente_id) references Cliente (id);
alter table OrdemDeServico add constraint FKr6s3o874lp26l7c5htt6ql9q3 foreign key (usuario_id) references Usuario (id);
alter table os_has_aparelho add constraint FKkjmovksevvep8lmlx2j98go0w foreign key (aparelho_id) references Aparelho (id);
alter table os_has_aparelho add constraint FK1nltffxe3iqlpjhfl9qfnxsye foreign key (ordemDeServico_id) references OrdemDeServico (id);
alter table Usuario_OrdemDeServico add constraint FKqp4r1e57ybgwh65ojkx5cktpp foreign key (listaOsCadastrada_id) references OrdemDeServico (id);
alter table Usuario_OrdemDeServico add constraint FKsnajuq2wkfrvesgo4wiqm7mje foreign key (Usuario_id) references Usuario (id);
